### ISSUE TITLE
How to get month wise air and water temperature.

### ISSUE THREAD

**Issue by riteshkhatri** [eigan/yr-php-library#11]
Hello,
I need to display month wise air and water temperature so how can i get current years monthly air and water temperatures.
Like,
January : 20(Celsius) Air temperature , 20(Celsius) water temperature
February : 20(Celsius) Air temperature , 20(Celsius) water temperature

**Comment by eigan** [comment]
Hello @riteshkhatri!

Unfortunately we don't support water temperature in this library (open for PR).

Looks like you can get the temperatures in XML format from here: https://om.yr.no/badetemperatur/badetemperatur.xml

**Comment by riteshkhatri** [comment]
Ohh,
but i want this periodically by month like yr.no statistics portion,
if you can help, 

![image_qi](https://user-images.githubusercontent.com/22073329/40111237-e2a537ba-591f-11e8-9a17-fc3a3a3151cf.png)

and i want to display it like this

![image_eu](https://user-images.githubusercontent.com/22073329/40111351-2daf982c-5920-11e8-85fe-f2a73da8ceee.png)

**Comment by eigan** [comment]
I don't think Yr actually provides temperature for that far into the future. I know for sure it doesnt give you previous months though.

**Comment by riteshkhatri** [comment]
Oh
then what to do now
i need current year all the months air and water average temperatures.
is there any one else can provide?
any help will be appreciated.
Then how they can get this?in this url [link](https://www.yr.no/place/United_States/New_York/New_York/statistics.html)

![image_8d](https://user-images.githubusercontent.com/22073329/40112035-5aabf0f8-5922-11e8-8249-90c17318b453.png)

please help.
sorry for my bad english and thank you sooo much for quick reply.i am searching for this till two days but no success. :(

**Comment by eigan** [comment]
> Then how they can get this?

Take a look at this api recently released by _Meteorologisk institutt_.  https://frost.met.no/index.html

> The Frost API provides free access to MET Norway's archive of historical weather and climate data. These data include quality controlled daily, monthly, and yearly measurements of temperature, precipitation, and wind data

_Meteorologisk institutt_ (MET) provides the data for this library.

Maybe its just for Norway, Iam not sure. You might find other services by using Google: https://www.google.com/search?q=historical+temperature+data+api

**Comment by riteshkhatri** [comment]
ohkey thank you so much. :)
