### ISSUE TITLE
Small mistakes

### ISSUE THREAD

**Issue by rasamax** [eigan/yr-php-library#3]
### Location.php:229
Change *!is_int($to)* to *!is_int($from)*
```php
$from = is_null($from) || !is_int($from) ? time() : $from;
```

### Location.php:233
Change *$forecast->getFrom()* to *$forecast->getTo()*
```php
$forecast->getTo()->getTimestamp() <= $to) {
```

**Comment by eigan** [comment]
Thank you. 

Dunno how I managed to write the one on line 229 :+1: 

I think 233 is right though? As the documentation on the method says:
```php
// @param  int        $to        unixtime for when the last forecast should start
```

So this means that a forecast should either start at the `$to` timestamp (is equal), or should be earlier (lower).
